version: "3"
services:
 SonarQube:
  depends_on:
  - db
  image: sonarqube
  environment:
  SONARQUBE_JDBC_URL: "jdbc:mysql://localhost:3306/sonar"
  SONARQUBE_JDBC_USERNAME: sonar
  SONARQUBE_JDBC_PASSWORD: sonar
  MYSQL_ROOT_PASSWORD: password
  MYSQL_USER: sonar
  MYSQL_PASSWORD: sonar
  volumes:
   - /opt/SonarQube/data:/opt/SonarQube/data
   - /opt/SonarQube/conf:/opt/SonarQube/conf
   - /opt/SonarQube/extensions:/opt/SonarQube/extensions
   - /opt/SonarQube/logs:/opt/SonarQube/logs
   - /opt/SonarQube/bundled-plugins:/opt/SonarQube/lib/bundled-plugins
  ports:
   - "9000:9000"
