version: "3"
services:
 SonarQube:
  image: sonarqube
  environment:
  SONAR_JDBC_URL: jdbc:sqllite://db:3306/sonar
  SONAR_JDBC_USERNAME: sonartest
  SONAR_JDBC_PASSWORD: sonartest
  volumes:
   - /opt/SonarQube/data:/opt/SonarQube/data
   - /opt/SonarQube/conf:/opt/SonarQube/conf
   - /opt/SonarQube/extensions:/opt/SonarQube/extensions
   - /opt/SonarQube/logs:/opt/SonarQube/logs
   - /opt/SonarQube/bundled-plugins:/opt/SonarQube/lib/bundled-plugins
  ports:
   - "9000:9000"
