version: "3"
services:
 SonarQube:
  image: sonarqube
  environment:
  SONAR_JDBC_URL: jdbc:sqllite://db:3306/sonar
  SONAR_JDBC_USERNAME: sonartest
  SONAR_JDBC_PASSWORD: sonartest
  volumes:
   - SonarQube_data:/opt/SonarQube/data
   - SonarQube_conf:/opt/SonarQube/conf
   - SonarQube_extensions:/opt/SonarQube/extensions
   - SonarQube_logs:/opt/SonarQube/logs
   - SonarQube_bundled-plugins:/opt/SonarQube/lib/bundled-plugins
  ports:
   - "9000:9000"
volumes:
  SonarQube_data:
  SonarQube_extensions:
  SonarQube_logs:
